/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfaceGrafica;

/**
 *
 * @author sarah
 */
public class TelaCadastro extends javax.swing.JFrame {

    /** Creates new form TelaEscolheCadastro */
    public TelaCadastro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastroJog = new javax.swing.JButton();
        botaoCadastroAdmin = new javax.swing.JButton();
        javax.swing.JButton botaoConsultarJog = new javax.swing.JButton();
        javax.swing.JButton botaoRemoveAdmin1 = new javax.swing.JButton();
        javax.swing.JButton botaoConsultaAdmin = new javax.swing.JButton();
        javax.swing.JButton botaoRemoveJog1 = new javax.swing.JButton();
        javax.swing.JButton botaoEditaJog = new javax.swing.JButton();
        javax.swing.JButton botaoEditaAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCadastroJog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCadastroJog.setText("Cadastrar Jogador");
        botaoCadastroJog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoCadastroJog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastroJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroJogActionPerformed(evt);
            }
        });

        botaoCadastroAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCadastroAdmin.setText("Cadastrar Administrador");
        botaoCadastroAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoCadastroAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastroAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroAdminActionPerformed(evt);
            }
        });

        botaoConsultarJog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoConsultarJog.setText("Consultar Jogador");
        botaoConsultarJog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoConsultarJog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConsultarJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarJogActionPerformed(evt);
            }
        });

        botaoRemoveAdmin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoRemoveAdmin1.setText("Remover Administrador");
        botaoRemoveAdmin1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoRemoveAdmin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoRemoveAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoveAdmin1ActionPerformed(evt);
            }
        });

        botaoConsultaAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoConsultaAdmin.setText("Consultar Administrador");
        botaoConsultaAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoConsultaAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConsultaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultaAdminActionPerformed(evt);
            }
        });

        botaoRemoveJog1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoRemoveJog1.setText("Remover Jogador");
        botaoRemoveJog1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoRemoveJog1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoRemoveJog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoveJog1ActionPerformed(evt);
            }
        });

        botaoEditaJog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoEditaJog.setText("Editar Jogador");
        botaoEditaJog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoEditaJog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEditaJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditaJogActionPerformed(evt);
            }
        });

        botaoEditaAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoEditaAdmin.setText("Editar Administrador");
        botaoEditaAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoEditaAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEditaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditaAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoRemoveAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botaoRemoveJog1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoCadastroAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botaoCadastroJog, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoConsultaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoEditaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoEditaJog, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoConsultarJog, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastroJog, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastroAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemoveAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemoveJog1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConsultaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsultarJog, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditaJog, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroJogActionPerformed
        TelaCadastroJogador frame = new TelaCadastroJogador();
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                frame.dispose();
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_botaoCadastroJogActionPerformed

    private void botaoCadastroAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroAdminActionPerformed
        TelaCadastroAdmin frame = new TelaCadastroAdmin();
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                frame.dispose();
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_botaoCadastroAdminActionPerformed

    private void botaoConsultarJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarJogActionPerformed
        TelaConsultaJogador frame = new TelaConsultaJogador();
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                frame.dispose();
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_botaoConsultarJogActionPerformed

    private void botaoRemoveAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoveAdmin1ActionPerformed
        TelaRemoveAdmin frame = new TelaRemoveAdmin();
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                frame.dispose();
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_botaoRemoveAdmin1ActionPerformed

    private void botaoConsultaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultaAdminActionPerformed
        TelaConsultaAdmin frame = new TelaConsultaAdmin();
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                frame.dispose();
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_botaoConsultaAdminActionPerformed

    private void botaoRemoveJog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoveJog1ActionPerformed
        TelaRemoveJogador frame = new TelaRemoveJogador();
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                frame.dispose();
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_botaoRemoveJog1ActionPerformed

    private void botaoEditaJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditaJogActionPerformed
        TelaEditaJogador frame = new TelaEditaJogador();
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                frame.dispose();
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_botaoEditaJogActionPerformed

    private void botaoEditaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditaAdminActionPerformed
        TelaEditaAdm frame = new TelaEditaAdm();
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                frame.dispose();
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_botaoEditaAdminActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastroAdmin;
    private javax.swing.JButton botaoCadastroJog;
    // End of variables declaration//GEN-END:variables

}
